[
  {
    "cmd": [],
    "name": "RECIPE CRASH (Uncaught exception)",
    "~followup_annotations": [
      "@@@STEP_EXCEPTION@@@",
      "The recipe has crashed at point 'Uncaught exception'!",
      "",
      "Traceback (most recent call last):",
      "  File \"RECIPE_REPO[recipe_engine]/recipe_engine/internal/engine.py\", line 564, in run_steps",
      "    raw_result = recipe_obj.run_steps(api, engine)",
      "  File \"RECIPE_REPO[recipe_engine]/recipe_engine/internal/recipe_deps.py\", line 733, in run_steps",
      "    properties_def, api=api)",
      "  File \"RECIPE_REPO[recipe_engine]/recipe_engine/internal/property_invoker.py\", line 89, in invoke_with_properties",
      "    arg_names, **additional_args)",
      "  File \"RECIPE_REPO[recipe_engine]/recipe_engine/internal/property_invoker.py\", line 52, in _invoke_with_properties",
      "    return callable_obj(*props, **additional_args)",
      "  File \"RECIPE_REPO[recipe_engine]/recipes/engine_tests/undeclared_method.py\", line 22, in RunSteps",
      "    api.missing_module('baz')",
      "  File \"RECIPE_REPO[recipe_engine]/recipe_engine/util.py\", line 53, in __getattr__",
      "    \"RecipeApi has no dependency %r. (Add it to DEPS?)\" % (key,))",
      "ModuleInjectionError: RecipeApi has no dependency 'missing_module'. (Add it to DEPS?)"
    ]
  },
  {
    "failure": {
      "humanReason": "Uncaught Exception: ModuleInjectionError(\"RecipeApi has no dependency 'missing_module'. (Add it to DEPS?)\",)"
    },
    "name": "$result"
  }
]