[
  {
    "failure": {
      "exception": {
        "traceback": [
          "<omitted by recipe engine>"
        ]
      },
      "humanReason": "Uncaught Exception: TypeError('BAD DOGE',)"
    },
    "name": "$result"
  }
]