[
  {
    "failure": {
      "humanReason": "Uncaught Exception: ValueError('URL must specify a network location.',)"
    },
    "name": "$result"
  }
]